spring.application.name=whatsap

spring.datasource.url=jdbc:postgresql://dpg-d8vu76e8bjmc738mvoi0-a:5432/bbdd_neumatica_whatsapp
spring.datasource.username=neumatica
spring.datasource.password=RptC4tx9XPHXk0yK9Bi1QQ0x8Hl4IVIz

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect