spring.application.name=whatsap

spring.datasource.url=jdbc:postgresql://dpg-d8vu76e8bjmc738mvoi0-a:5432/bbdd_neumatica_whatsapp
#spring.datasource.username=neumatica
#spring.datasource.password=RptC4tx9XPHXk0yK9Bi1QQ0x8Hl4IVIz

#spring.datasource.url=jdbc:postgresql://dpg-d8vu76e8bjmc738mvoi0-a.oregon-postgres.render.com.:5432/bbdd_neumatica_whatsapp
spring.datasource.username=neumatica
spring.datasource.password=RptC4tx9XPHXk0yK9Bi1QQ0x8Hl4IVIz

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=CAMBIA_ESTA_CLAVE_POR_UNA_MUY_LARGA_Y_SEGURA
app.jwt.issuer=security-service
app.jwt.public-key=classpath:keys/public.pem

security.service.url=https://security-service-neumatica.onrender.com